--TABLES
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_login TEXT UNIQUE NOT NULL,
  hashed_password TEXT NOT NULL,
  display_name TEXT,
  dollars INTEGER DEFAULT 100,
  cents INTEGER DEFAULT 0
);
