--TABLES
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_login TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'user' NOT NULL,
  hashed_password TEXT NOT NULL,
  dollars INTEGER DEFAULT 100 NOT NULL,
  cents INTEGER DEFAULT 0 NOT NULL
);
