--TABLES
CREATE TABLE IF NOT EXISTS stock (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  image_path TEXT,
);

CREATE TABLE IF NOT EXISTS stock_data (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stock_id INTEGER NOT NULL,
  event_label TEXT NOT NULL,
  value_dollars REAL NOT NULL,
  value_cents REAL NOT NULL,
  sequence INTEGER NOT NULL AUTOINCREMENT,
  FOREIGN KEY (stock_id) REFERENCES stocks (id)
);
