// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
	"database/sql"
)

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET
  role = COALESCE(?1, role),
  dollars = COALESCE(?2, dollars),
  cents = COALESCE(?3, cents)
WHERE
  user_login = ?4 RETURNING id, user_login, role, hashed_password, dollars, cents
`

type AdminUpdateUserParams struct {
	Role      sql.NullString `json:"role"`
	Dollars   sql.NullInt64  `json:"dollars"`
	Cents     sql.NullInt64  `json:"cents"`
	UserLogin string         `json:"user_login"`
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminUpdateUser,
		arg.Role,
		arg.Dollars,
		arg.Cents,
		arg.UserLogin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.Role,
		&i.HashedPassword,
		&i.Dollars,
		&i.Cents,
	)
	return i, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO
  users (user_login, role, hashed_password, dollars, cents)
VALUES
  (?, ?, ?, ?, ?) RETURNING id, user_login, role, hashed_password, dollars, cents
`

type CreateAdminParams struct {
	UserLogin      string `json:"user_login"`
	Role           string `json:"role"`
	HashedPassword string `json:"hashed_password"`
	Dollars        int64  `json:"dollars"`
	Cents          int64  `json:"cents"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createAdmin,
		arg.UserLogin,
		arg.Role,
		arg.HashedPassword,
		arg.Dollars,
		arg.Cents,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.Role,
		&i.HashedPassword,
		&i.Dollars,
		&i.Cents,
	)
	return i, err
}
