// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Migration struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	AppliedAt sql.NullTime `json:"applied_at"`
}

type Session struct {
	ID           interface{} `json:"id"`
	UserLogin    string      `json:"user_login"`
	RefreshToken string      `json:"refresh_token"`
	UserAgent    string      `json:"user_agent"`
	ClientIp     string      `json:"client_ip"`
	IsBlocked    int64       `json:"is_blocked"`
	ExpiresAt    time.Time   `json:"expires_at"`
	CreatedAt    time.Time   `json:"created_at"`
}

type SiteSetting struct {
	ID                    int64     `json:"id"`
	NumberOfEventsVisible int64     `json:"number_of_events_visible"`
	ValueSymbol           string    `json:"value_symbol"`
	EventLabel            string    `json:"event_label"`
	Lockout               int64     `json:"lockout"`
	LockoutTimeStart      time.Time `json:"lockout_time_start"`
}

type Stock struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	ImagePath sql.NullString `json:"image_path"`
}

type StockDatum struct {
	ID           int64  `json:"id"`
	StockID      int64  `json:"stock_id"`
	EventLabel   string `json:"event_label"`
	ValueDollars int64  `json:"value_dollars"`
	ValueCents   int64  `json:"value_cents"`
}

type User struct {
	ID             int64  `json:"id"`
	UserLogin      string `json:"user_login"`
	Role           string `json:"role"`
	HashedPassword string `json:"hashed_password"`
	Dollars        int64  `json:"dollars"`
	Cents          int64  `json:"cents"`
}

type UserStock struct {
	UserID   int64 `json:"user_id"`
	StockID  int64 `json:"stock_id"`
	Quantity int64 `json:"quantity"`
}
