// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type SiteSetting struct {
	ID                    int64
	NumberOfEventsVisible sql.NullInt64
	ValueSymbol           interface{}
	EventLabel            interface{}
	LockoutTimeStart      sql.NullTime
}

type Stock struct {
	ID        int64
	Name      string
	ImagePath sql.NullString
}

type StockDatum struct {
	ID           int64
	StockID      int64
	EventLabel   string
	ValueDollars int64
	ValueCents   int64
}

type User struct {
	ID             int64
	UserLogin      string
	HashedPassword string
	DisplayName    sql.NullString
	Dollars        sql.NullInt64
	Cents          sql.NullInt64
}

type UserStock struct {
	UserID   int64
	StockID  int64
	Quantity int64
}
