// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CreateSiteSettings(ctx context.Context, arg CreateSiteSettingsParams) (SiteSetting, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error)
	CreateStockData(ctx context.Context, arg CreateStockDataParams) (StockDatum, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserStock(ctx context.Context, arg CreateUserStockParams) (UserStock, error)
	DeleteStock(ctx context.Context, name string) error
	DeleteUserStock(ctx context.Context, arg DeleteUserStockParams) error
	EventLabel(ctx context.Context) (interface{}, error)
	GetLockoutTime(ctx context.Context) (time.Time, error)
	GetNumberEvents(ctx context.Context) (int64, error)
	GetSiteSettings(ctx context.Context) (SiteSetting, error)
	GetStockData(ctx context.Context, arg GetStockDataParams) (StockDatum, error)
	GetStockFromId(ctx context.Context, id int64) (Stock, error)
	GetStockFromName(ctx context.Context, name string) (Stock, error)
	GetUserFromId(ctx context.Context, id int64) (User, error)
	GetUserFromName(ctx context.Context, userLogin string) (User, error)
	GetUserStock(ctx context.Context, arg GetUserStockParams) (UserStock, error)
	GetValueSymbol(ctx context.Context) (interface{}, error)
	PruneStockData(ctx context.Context, arg PruneStockDataParams) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (SiteSetting, error)
	UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error)
	UpdateStockData(ctx context.Context, arg UpdateStockDataParams) (StockDatum, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserStock(ctx context.Context, arg UpdateUserStockParams) (UserStock, error)
}

var _ Querier = (*Queries)(nil)
