// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO
  sessions (
    id,
    user_login,
    refresh_token,
    user_agent,
    client_ip,
    is_blocked,
    expires_at
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?) RETURNING id, user_login, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	ID           interface{} `json:"id"`
	UserLogin    string      `json:"user_login"`
	RefreshToken string      `json:"refresh_token"`
	UserAgent    string      `json:"user_agent"`
	ClientIp     string      `json:"client_ip"`
	IsBlocked    int64       `json:"is_blocked"`
	ExpiresAt    time.Time   `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserLogin,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT
  id, user_login, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
FROM
  sessions
WHERE
  user_login = ?
LIMIT
  1
`

func (q *Queries) GetSession(ctx context.Context, userLogin string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, userLogin)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
