// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: site_settings.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSiteSettings = `-- name: CreateSiteSettings :one
INSERT INTO
  site_settings (
    number_of_events_visible,
    value_symbol,
    event_label,
    lockout_time_start
  )
VALUES
  (?, ?, ?, ?) RETURNING id, number_of_events_visible, value_symbol, event_label, lockout_time_start
`

type CreateSiteSettingsParams struct {
	NumberOfEventsVisible int64
	ValueSymbol           interface{}
	EventLabel            interface{}
	LockoutTimeStart      time.Time
}

func (q *Queries) CreateSiteSettings(ctx context.Context, arg CreateSiteSettingsParams) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, createSiteSettings,
		arg.NumberOfEventsVisible,
		arg.ValueSymbol,
		arg.EventLabel,
		arg.LockoutTimeStart,
	)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.NumberOfEventsVisible,
		&i.ValueSymbol,
		&i.EventLabel,
		&i.LockoutTimeStart,
	)
	return i, err
}

const eventLabel = `-- name: EventLabel :one
SELECT
  event_label
FROM
  site_settings
LIMIT
  1
`

func (q *Queries) EventLabel(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, eventLabel)
	var event_label interface{}
	err := row.Scan(&event_label)
	return event_label, err
}

const getLockoutTime = `-- name: GetLockoutTime :one
SELECT
  lockout_time_start
FROM
  site_settings
LIMIT
  1
`

func (q *Queries) GetLockoutTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLockoutTime)
	var lockout_time_start time.Time
	err := row.Scan(&lockout_time_start)
	return lockout_time_start, err
}

const getNumberEvents = `-- name: GetNumberEvents :one
SELECT
  number_of_events_visible
FROM
  site_settings
LIMIT
  1
`

func (q *Queries) GetNumberEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumberEvents)
	var number_of_events_visible int64
	err := row.Scan(&number_of_events_visible)
	return number_of_events_visible, err
}

const getValueSymbol = `-- name: GetValueSymbol :one
SELECT
  value_symbol
FROM
  site_settings
LIMIT
  1
`

func (q *Queries) GetValueSymbol(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getValueSymbol)
	var value_symbol interface{}
	err := row.Scan(&value_symbol)
	return value_symbol, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE site_settings
SET
  number_of_events_visible = COALESCE(
    ?1,
    number_of_events_visible
  ),
  value_symbol = COALESCE(?2, value_symbol),
  event_label = COALESCE(?3, event_label),
  lockout_time_start = COALESCE(
    ?4,
    lockout_time_start
  )
WHERE
  id = 0 RETURNING id, number_of_events_visible, value_symbol, event_label, lockout_time_start
`

type UpdateSettingsParams struct {
	NumberOfEventsVisible sql.NullInt64
	ValueSymbol           interface{}
	EventLabel            interface{}
	LockoutTimeStart      sql.NullTime
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.NumberOfEventsVisible,
		arg.ValueSymbol,
		arg.EventLabel,
		arg.LockoutTimeStart,
	)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.NumberOfEventsVisible,
		&i.ValueSymbol,
		&i.EventLabel,
		&i.LockoutTimeStart,
	)
	return i, err
}
