// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocks.sql

package db

import (
	"context"
	"database/sql"
)

const createStock = `-- name: CreateStock :exec
INSERT INTO
  stocks (name, image_path)
VALUES
  (?, ?)
`

type CreateStockParams struct {
	Name      string
	ImagePath sql.NullString
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) error {
	_, err := q.db.ExecContext(ctx, createStock, arg.Name, arg.ImagePath)
	return err
}

const createStockData = `-- name: CreateStockData :exec
INSERT INTO
  stock_data (
    stock_id,
    event_label,
    value_dollars,
    value_cents,
    sequence
  )
VALUES
  (?, ?, ?, ?, ?)
`

type CreateStockDataParams struct {
	StockID      int64
	EventLabel   string
	ValueDollars int64
	ValueCents   int64
	Sequence     int64
}

func (q *Queries) CreateStockData(ctx context.Context, arg CreateStockDataParams) error {
	_, err := q.db.ExecContext(ctx, createStockData,
		arg.StockID,
		arg.EventLabel,
		arg.ValueDollars,
		arg.ValueCents,
		arg.Sequence,
	)
	return err
}

const getStock = `-- name: GetStock :one
SELECT
  id, name, image_path
FROM
  stocks
WHERE
  name = ?
LIMIT
  1
`

func (q *Queries) GetStock(ctx context.Context, name string) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStock, name)
	var i Stock
	err := row.Scan(&i.ID, &i.Name, &i.ImagePath)
	return i, err
}

const getStockData = `-- name: GetStockData :one
SELECT
  id, stock_id, event_label, value_dollars, value_cents, sequence
FROM
  stock_data
WHERE
  stock_id = ?
ORDER BY
  sequence ASC
LIMIT
  ?
`

type GetStockDataParams struct {
	StockID int64
	Limit   int64
}

func (q *Queries) GetStockData(ctx context.Context, arg GetStockDataParams) (StockDatum, error) {
	row := q.db.QueryRowContext(ctx, getStockData, arg.StockID, arg.Limit)
	var i StockDatum
	err := row.Scan(
		&i.ID,
		&i.StockID,
		&i.EventLabel,
		&i.ValueDollars,
		&i.ValueCents,
		&i.Sequence,
	)
	return i, err
}

const pruneStockData = `-- name: PruneStockData :exec
DELETE FROM stock_data
WHERE
  stock_data.stock_id = ?
  AND stock_data.id NOT IN (
    SELECT
      sd.id
    FROM
      stock_data as sd
    WHERE
      sd.stock_id = ?
    ORDER BY
      sd.sequence DESC
    LIMIT
      ?
  )
`

type PruneStockDataParams struct {
	StockID   int64
	StockID_2 int64
	Limit     int64
}

func (q *Queries) PruneStockData(ctx context.Context, arg PruneStockDataParams) error {
	_, err := q.db.ExecContext(ctx, pruneStockData, arg.StockID, arg.StockID_2, arg.Limit)
	return err
}

const updateStock = `-- name: UpdateStock :one
UPDATE stocks
SET
  name = COALESCE(?1, name),
  image_path = COALESCE(?2, image_path)
WHERE
  name = ?3 RETURNING id, name, image_path
`

type UpdateStockParams struct {
	NewName   sql.NullString
	ImagePath sql.NullString
	Name      string
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStock, arg.NewName, arg.ImagePath, arg.Name)
	var i Stock
	err := row.Scan(&i.ID, &i.Name, &i.ImagePath)
	return i, err
}
