// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_stocks.sql

package db

import (
	"context"
)

const createUserStock = `-- name: CreateUserStock :one
INSERT INTO
  user_stocks (user_id, stock_id, quantity)
VALUES
  (?, ?, ?) RETURNING user_id, stock_id, quantity
`

type CreateUserStockParams struct {
	UserID   int64 `json:"user_id"`
	StockID  int64 `json:"stock_id"`
	Quantity int64 `json:"quantity"`
}

func (q *Queries) CreateUserStock(ctx context.Context, arg CreateUserStockParams) (UserStock, error) {
	row := q.db.QueryRowContext(ctx, createUserStock, arg.UserID, arg.StockID, arg.Quantity)
	var i UserStock
	err := row.Scan(&i.UserID, &i.StockID, &i.Quantity)
	return i, err
}

const deleteUserStock = `-- name: DeleteUserStock :exec
DELETE FROM user_stocks
WHERE
  user_id = ?
  AND stock_id = ?
  AND quantity = 0
`

type DeleteUserStockParams struct {
	UserID  int64 `json:"user_id"`
	StockID int64 `json:"stock_id"`
}

func (q *Queries) DeleteUserStock(ctx context.Context, arg DeleteUserStockParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserStock, arg.UserID, arg.StockID)
	return err
}

const getUserStock = `-- name: GetUserStock :one
SELECT
  user_id, stock_id, quantity
FROM
  user_stocks
WHERE
  user_id = ?
  AND stock_id = ?
LIMIT
  1
`

type GetUserStockParams struct {
	UserID  int64 `json:"user_id"`
	StockID int64 `json:"stock_id"`
}

func (q *Queries) GetUserStock(ctx context.Context, arg GetUserStockParams) (UserStock, error) {
	row := q.db.QueryRowContext(ctx, getUserStock, arg.UserID, arg.StockID)
	var i UserStock
	err := row.Scan(&i.UserID, &i.StockID, &i.Quantity)
	return i, err
}

const updateUserStock = `-- name: UpdateUserStock :one
UPDATE user_stocks
SET
  quantity = ?1
WHERE
  user_id = ?2
  AND stock_id = ?3 RETURNING user_id, stock_id, quantity
`

type UpdateUserStockParams struct {
	Quantity int64 `json:"quantity"`
	UserID   int64 `json:"user_id"`
	StockID  int64 `json:"stock_id"`
}

func (q *Queries) UpdateUserStock(ctx context.Context, arg UpdateUserStockParams) (UserStock, error) {
	row := q.db.QueryRowContext(ctx, updateUserStock, arg.Quantity, arg.UserID, arg.StockID)
	var i UserStock
	err := row.Scan(&i.UserID, &i.StockID, &i.Quantity)
	return i, err
}
