// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO
  users (
    user_login,
    hashed_password,
    display_name,
    dollars,
    cents
  )
VALUES
  (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	UserLogin      string
	HashedPassword string
	DisplayName    sql.NullString
	Dollars        sql.NullInt64
	Cents          sql.NullInt64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserLogin,
		arg.HashedPassword,
		arg.DisplayName,
		arg.Dollars,
		arg.Cents,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT
  id, user_login, hashed_password, display_name, dollars, cents
FROM
  users
WHERE
  user_login = ?
LIMIT
  1
`

func (q *Queries) GetUser(ctx context.Context, userLogin string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userLogin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.HashedPassword,
		&i.DisplayName,
		&i.Dollars,
		&i.Cents,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  hashed_password = COALESCE(?1, hashed_password),
  display_name = COALESCE(?2, full_name),
  dollars = COALESCE(?3, dollars),
  cents = COALESCE(?4, cents)
WHERE
  user_login = ?5 RETURNING id, user_login, hashed_password, display_name, dollars, cents
`

type UpdateUserParams struct {
	HashedPassword sql.NullString
	FullName       sql.NullString
	Dollars        sql.NullInt64
	Cents          sql.NullInt64
	UserLogin      string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.HashedPassword,
		arg.FullName,
		arg.Dollars,
		arg.Cents,
		arg.UserLogin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.HashedPassword,
		&i.DisplayName,
		&i.Dollars,
		&i.Cents,
	)
	return i, err
}
