// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (user_login, hashed_password, dollars, cents)
VALUES
  (?, ?, ?, ?) RETURNING id, user_login, hashed_password, dollars, cents
`

type CreateUserParams struct {
	UserLogin      string
	HashedPassword string
	Dollars        sql.NullInt64
	Cents          sql.NullInt64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserLogin,
		arg.HashedPassword,
		arg.Dollars,
		arg.Cents,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.HashedPassword,
		&i.Dollars,
		&i.Cents,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
  id, user_login, hashed_password, dollars, cents
FROM
  users
WHERE
  user_login = ?
LIMIT
  1
`

func (q *Queries) GetUser(ctx context.Context, userLogin string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userLogin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.HashedPassword,
		&i.Dollars,
		&i.Cents,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  hashed_password = COALESCE(?1, hashed_password),
  dollars = COALESCE(?2, dollars),
  cents = COALESCE(?3, cents)
WHERE
  user_login = ?4 RETURNING id, user_login, hashed_password, dollars, cents
`

type UpdateUserParams struct {
	HashedPassword sql.NullString
	Dollars        sql.NullInt64
	Cents          sql.NullInt64
	UserLogin      string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.HashedPassword,
		arg.Dollars,
		arg.Cents,
		arg.UserLogin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.HashedPassword,
		&i.Dollars,
		&i.Cents,
	)
	return i, err
}
